version: '3.8'

services:
  web:
    image: frdbadmin-front-dev:0.1
    build:
      context: front-end
      args:
        - PUID=1024
        - PGID=1024
    container_name: frdba-dev-web
    ports:
      - '127.0.0.1:35000:22'
      - '127.0.0.1:35000:80'
    volumes:
      - $(pwd)/app:/app
    networks:
      - frdba-dev-net
    restart: unless-stopped

  api:
    image: frdbadmin-api-dev:0.1
    build:
      context: api
      args:
        - PUID=1000
        - PGID=984
      target: dev
    container_name: frdba-dev-api
    ports:
      - '127.0.0.1:34100:22'
      - '127.0.0.1:34000:5046'
    volumes:
      - $(pwd)/api:/app
    networks:
      - frdba-dev-net
    restart: unless-stopped

  psqldb:
    image: postgres:15.4-alpine
    container_name: frdba-dev-psqldb
    ports:
      - '127.0.0.1:33000:5432'
    volumes:
      - $(pwd)/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=db_frdbadmin
    networks:
      - frdba-dev-net
    restart: unless-stopped

networks:
  frdba-dev-net:
    name: frdba-dev-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
